const images = [
    // 'https://imgur.com/Bll5xtz.jpg',
    // 'https://imgur.com/irYtls6.jpg',
    // 'https://imgur.com/J9CuDRy.jpg',
    // 'https://imgur.com/UtISt9D.jpg',
    // 'https://imgur.com/yrUHwWZ.jpg',
    // 'https://imgur.com/lj5J75z.jpg',
    // 'https://imgur.com/WgFjIUx.jpg',
    // 'https://imgur.com/MopqigP.jpg',
    // 'https://imgur.com/IAWFt7g.jpg',
    // 'https://imgur.com/o0bg2GI.jpg',
    // 'https://imgur.com/XLQMQOw.jpg',
    'https://imgur.com/6oSAHMu.jpg',
    'https://imgur.com/xmDPyCq.jpg',
    'https://imgur.com/hCerywg.jpg',
    'https://imgur.com/ChTMILS.jpg',
    'https://imgur.com/mH11Oem.jpg',
    'https://imgur.com/6Rb4PRG.jpg',
    'https://imgur.com/cqcK7vq.jpg',
    'https://imgur.com/GjNhlTi.jpg',
    'https://imgur.com/f0SCmew.jpg',
    'https://imgur.com/GupvA9b.jpg',
    'https://imgur.com/hJ42vaI.jpg',
    'https://imgur.com/Hi5TAAF.jpg',
    'https://imgur.com/HZjKiw0.jpg',
    'https://imgur.com/Kx9PvSc.jpg',
    'https://imgur.com/2MoESLN.jpg',
    'https://imgur.com/HPHQg8y.jpg',
    'https://imgur.com/rZYazo4.jpg',
    'https://imgur.com/FzWXpa6.jpg',
    'https://imgur.com/7oa6kFp.jpg',
    'https://imgur.com/LWF1fAZ.jpg',
    'https://imgur.com/wtTf4I1.jpg',
    'https://imgur.com/Dr7P3cx.jpg',
    'https://imgur.com/tXXK2xB.jpg',
    'https://imgur.com/lghHQtX.jpg',
    'https://imgur.com/8ctz8bs.jpg',
    'https://imgur.com/ujCihgd.jpg',
    'https://imgur.com/D2gk6ja.jpg',
    'https://imgur.com/ABavO6L.jpg',
    'https://imgur.com/WzQeNyn.jpg',
    'https://imgur.com/h39kCzm.jpg',
    'https://imgur.com/mGrF7m5.jpg',
    'https://imgur.com/BuEtayb.jpg',
    'https://imgur.com/UO0gyeI.jpg',
    'https://imgur.com/CcwNmMv.jpg',
    'https://imgur.com/MHeQckG.jpg',
    'https://imgur.com/obP8eaR.jpg',
    'https://imgur.com/5TRPsf8.jpg',
    'https://imgur.com/CVVm7PT.jpg',
    'https://imgur.com/WShEIUe.jpg',
    'https://imgur.com/ECXoDQF.jpg',
    'https://imgur.com/NXOxgyB.jpg',
    'https://imgur.com/PHts4Nd.jpg',
    'https://imgur.com/vFOo5PZ.jpg',
    'https://imgur.com/huUQG0V.jpg',
    'https://imgur.com/yjI1cZ2.jpg',
    'https://imgur.com/08QG6Yk.jpg',
    'https://imgur.com/nv64Q7p.jpg',
    'https://imgur.com/RHmNgCa.jpg',
    'https://imgur.com/vxhGVkw.jpg',
    'https://imgur.com/xzsoago.jpg',
    'https://imgur.com/rgnHjtD.jpg',
    'https://imgur.com/obNAEMz.jpg',
    'https://imgur.com/X5xGDBn.jpg',
    'https://imgur.com/twXwHNO.jpg',
    'https://imgur.com/G8fIZcU.jpg',
    'https://imgur.com/tvn9c2b.jpg',
    'https://imgur.com/9UgiESb.jpg',
    'https://imgur.com/93SKVku.jpg',
    'https://imgur.com/GdvloF2.jpg',
    'https://imgur.com/4z6gYut.jpg',
    'https://imgur.com/QoHYUZW.jpg',
    'https://imgur.com/fvSSm5a.jpg',
    'https://imgur.com/5MrnpGJ.jpg',
    'https://imgur.com/fTVcyGo.jpg',
    'https://imgur.com/KOQsHn7.jpg',
    'https://imgur.com/tGISg7x.jpg',
    'https://imgur.com/D2myctp.jpg',
    'https://imgur.com/X8gTuFi.jpg',
    'https://imgur.com/PWlLOxe.jpg',
    'https://imgur.com/sOeOlWd.jpg',
    'https://imgur.com/JeoWRYc.jpg',
    'https://imgur.com/kP7xoeZ.jpg',
    'https://imgur.com/PBxjNri.jpg',
    'https://imgur.com/SUHui7q.jpg',
    'https://imgur.com/R2W4o2v.jpg',
    'https://imgur.com/6Hz84mG.jpg',
    'https://imgur.com/DQiZ7jb.jpg',
    'https://imgur.com/Cjo5GZa.jpg',
    'https://imgur.com/zweiUfz.jpg',
    'https://imgur.com/pKmlO98.jpg',
    'https://imgur.com/WBmmjA6.jpg',
    'https://imgur.com/Une6CV3.jpg',
    'https://imgur.com/lQKEoZi.jpg',
    'https://imgur.com/B5Z4sNk.jpg',
    'https://imgur.com/qkoMmAd.jpg',
    'https://imgur.com/KZ6VkBY.jpg',
    'https://imgur.com/0nRNvWu.jpg'
  ];

  module.exports = images
